### ISSUE TITLE
Latest 1.3.0 `vaadin-overlay` release breaks `context-menu`

### ISSUE THREAD

**Issue by galanovnick** [vaadin/vaadin-context-menu#101]
Hello,

with latest 1.3.0 overlay release `context-menu` became really weird. It seems like added `flexbox` property brings additional shadowed rectangle with viewport size.

https://jsfiddle.net/vws1084p/1/

**Comment by platosha** [comment]
@galanovnick sorry about this. Please use a master `context-menu` or downgrade to latest stable release `v2.0.0` for now. Another alpha release with fixes is coming soon.

**Comment by platosha** [comment]
Fixed by #99

**Comment by platosha** [comment]
The fix is released in [v3.0.0-alpha3](https://github.com/vaadin/vaadin-context-menu/releases/tag/v3.0.0-alpha3).
