### ISSUE TITLE
JavaScript API `open` works incorrectly with a keyboard click event

### ISSUE THREAD

**Issue by galanovnick** [vaadin/vaadin-context-menu#103]
Hi,

I've discovered a misleading behavior when `context-menu` is opened using `open` method. If you click a button with a keyboard (i.e. move focus to the button and press `enter`), `context-menu` will have a completely incorrect position (left corner of the viewport).

You can easily reproduce this bug in the demo (https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-context-menu/demo/#javascript-api). Just focus the button and press `enter`.

Actually, this behavior is pretty obvious as long as `menu` position is calculated using `MouseEvent` `x` and `y` properties (or `offsetX`, `offsetY`). Consider using more flexible approach to determine event target position (maybe using target `boundingClientRect`?).

Thanks!

**Comment by platosha** [comment]
Hi, thanks for reporting.

In this case using event target position seems reasonable.

We are touch on schedule right now though. I’ll leave this open so that we don’t forget to come back to this.

A pull request with a fix is also welcome.

**Comment by jouni** [comment]
Not sure why this wasn’t marked as related to #153

**Comment by web-padawan** [comment]
Thanks, #153 is indeed a duplicate.

**Comment by web-padawan** [comment]
Closing this one as there was a recent discussion at #153 so let's continue there.
