### ISSUE TITLE
Unused `iron-overlay-behavior` dependency

### ISSUE THREAD

**Issue by galanovnick** [vaadin/vaadin-context-menu#114]
Hello.
Is there any reason to have this `iron-overlay-behavior` dependency? It's unclear where it's used.
Is `vaadin-context-menu` actually use this dependency, or is it just some stale artifact from old versions?

**Comment by samiheikki** [comment]
Looks like it was used in https://github.com/vaadin/vaadin-context-menu/commit/4f8798998c4ad4aacb4b3675dd596225e815bfa7#diff-66a399af7bafbcfacad65a17d9eb94c8, but not since v3.0.0-alpha2 version
