### ISSUE TITLE
vaadin-list-box is not focused when the overlay is opened for the first time

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-context-menu#116]
An error is logged to the console when opening the overlay for the first time:
<img width="625" alt="screen shot 2017-11-15 at 0 16 07" src="https://user-images.githubusercontent.com/66382/32807945-416873cc-c99a-11e7-88d0-d64950095ac2.png">

**Comment by manolo** [comment]
Wrong repo?

**Comment by manolo** [comment]
moved to https://github.com/vaadin/vaadin-list-box/issues/13

**Comment by jouni** [comment]
> Wrong repo?

Well, I encountered the issue only when used together with context menu, so I thought it was the appropriate place.

**Comment by manolo** [comment]
Gotcha, actually seems an issue in the list-mixin so also not the correct repo either :-(
