### ISSUE TITLE
open on left side of cursor if it would colapse

### ISSUE THREAD

**Issue by sickinga** [vaadin/vaadin-context-menu#140]
It would be cool if the context menu opens on the left side of the cursor if there isnt enought space on the right side or even something trivial like if the cursor is on the right 50% of the screen.

Here you can see how it should look like:
![image](https://user-images.githubusercontent.com/29484672/36548645-20cfcf5c-17f1-11e8-8b69-c028bacc0407.png)

Here how it does if there isnt enought space:
![image](https://user-images.githubusercontent.com/29484672/36548617-0fca923c-17f1-11e8-852a-e7366b5c784f.png)

**Comment by web-padawan** [comment]
The same bug is submitted in #115 which is in our backlog already. Closing as a duplicate.
