### ISSUE TITLE
Position incorrect when opened from keyboard

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-context-menu#153]
When the `click` event is used for `openOn` property, and gets produced by the <kbd>Spacebar</kbd> or <kbd>Enter</kbd> key, the event object does not contains coordinates, and the menu is not positioned:

![contextmenu](https://user-images.githubusercontent.com/10589913/39110534-2c75ff80-46da-11e8-80e5-a98dd1114f6d.gif)

This could be relevant for users attempting to implement something like `<vaadin-menu-button>` by using button and context-menu together. We should either document the missing feature, or fix it.

**Comment by jouni** [comment]
My suggestion is to fix this by positioning the menu close to (under?) the `selector` element on which the click event is listened to.

**Comment by brp-jimmy** [comment]
We would like to be able to control the position of the context menu as well.

Our use case is to have the component open as an options menu below the button when the user clicks it. I have been trying to change the position on the click event, but that is not allowed due to the properties being read only.

**Comment by heruan** [comment]
Found this looking for a way to position the menu (same use case a @brp-jimmy). Is this the right issue to subscribe about positioning or should be another one (existing or new)?

**Comment by jouni** [comment]
@heruan I think this is the closest related issue at the moment. We could create a more generic issue about positioning, and link this issue there. Might be better to collect use cases in another issue, than bundle them together with this bug issue?

**Comment by jouni** [comment]
> Our use case is to have the component open as an options menu below the button when the user clicks it. I have been trying to change the position on the click event, but that is not allowed due to the properties being read only.

Just noticed that I had prototyped this with a different use case (tried to build a hierarchical menu using nested context menus):

```javascript
const coords = button.getBoundingClientRect();

contextMenu.open({
  target: button,
  clientX: coords.left,
  clientY: coords.top + coords.height,
  preventDefault: () => {},
  stopPropagation: () => {}
});
```

So, you should be able to do a similar thing in your click listener, that you pass a fake event object for the `contextMenu.open()` method.
