### ISSUE TITLE
DX testing

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-context-menu#18]

**Comment by samiheikki** [comment]
Test plan: https://docs.google.com/document/d/1fa4q309j84wYYdV0IDZqV5hKxbeGtm0YctJ3H3tc5bs/edit

**Comment by samiheikki** [comment]
Please review the plan and if seems OK put back to top of next column so we can then organize DX testing

**Comment by tomivirkki** [comment]
Needs more tasks (currently only 1). See the documentation and demo to derive more test cases.

**Comment by samiheikki** [comment]
@tomivirkki The current task kinda has multiple mini tasks inside it.
- Add context menu
- Add items inside it
- Handle items click inside context menu

**Comment by tomivirkki** [comment]
I meant thing like configuring 'open-on', 'listen-on', 'close-on' and 'selector' properties, having a context-menu separate from the target element...

**Comment by samiheikki** [comment]
OK. I'll add more tests

**Comment by samiheikki** [comment]
@tomivirkki done

**Comment by samiheikki** [comment]
For the person conducting the DX testing: Document with all necessary info:  https://docs.google.com/document/d/1fa4q309j84wYYdV0IDZqV5hKxbeGtm0YctJ3H3tc5bs/edit
