### ISSUE TITLE
Lumo Dark doesn't work in flow production

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-context-menu#199]
When running with flow in production mode the style:
https://github.com/vaadin/vaadin-context-menu/blob/master/src/vaadin-context-menu-overlay.html#L27

is applied last and breaks lumo dark theme

**Comment by web-padawan** [comment]
Tried in https://taskmob.demo.vaadin.com/ and everything looks good now: 

![taskmob](https://user-images.githubusercontent.com/10589913/74517854-8e664600-4f1b-11ea-90d7-8fe3dafd8239.png)

The line mentioned in the original issue is this one:
https://github.com/vaadin/vaadin-context-menu/blob/080e93077f3e92d4f2fa2ac7032bd2bd1f565579/src/vaadin-context-menu-overlay.html#L27

And it is no longer applied last according to the dev tools:

![Screenshot 2020-02-14 at 11 20 17](https://user-images.githubusercontent.com/10589913/74518166-03d21680-4f1c-11ea-8bd2-f3c451253f28.png)

Closing as fixed.
