### ISSUE TITLE
Rename to vaadin-context-overlay?

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-context-menu#21]
Rename the current element to vaadin-context-overlay, as it doesn't by itself produce any menu.

This allows us to add an actual vaadin-context-menu element in the future, which is more opinionated about it’s content (like a hierarchical menu structure).

**Comment by platosha** [comment]
The current element is not just the overlay as well. As for me, it is more like `vaadin-context-menu-controller`, since it bothers with things like event listening, template rendering and bindings. Also, there is an actual overlay in a separate element.

**Comment by manolo** [comment]
event-listening, template-rendering and bindings are not specific of menus.
Shouldn't this element work as well for hosting for instance a color picker or a color magnifying glass like in some demo I saw from @Saulis  ?

**Comment by jouni** [comment]
I think my main point is that we should not reserve the `vaadin-context-menu` name for this rather general purpose element. 

I’m not expecting us to promote this general purpose element separately, it’s fine to be an internal implementation detail at this point. The repo name can still be vaadin-context-menu, and the main element that comes out (similar to paper-input vs. paper-input-container).

**Comment by Saulis** [comment]
After discussing, we decided to go ahead with a MVP `<vaadin-context-menu>` using a generic API. After getting more information from the users about their use cases, we can later on refine the API to a more menu-like approach, additionally perhaps chipping out a separate overlay element.
