### ISSUE TITLE
Context menu doesn't stay open on FF

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu#214]
Open the first demo on Firefox. Open the context menu.

Result: It opens and closes immediately

Expected: It opens and stays open

This occurs on pretty much every version of the component. Tested on Firefox 66

**Comment by web-padawan** [comment]
Confirmed it is broken in Firefox 66 beta, interestingly does not close when in "mobile" mode (once the viewport is small enough). Works in 65 stable version though. Investigating.

**Comment by tomivirkki** [comment]
It's also reproducible in 65 for me

**Comment by web-padawan** [comment]
Found out that for some weird reason the `e.preventDefault` somehow still leaks the global `click` event, which is picked up by `vaadin-overlay` so the `outsideClickListener` is called. I'm really surprised that it doesn't cause any test failure though. Working on a proper test case now.

**Comment by web-padawan** [comment]
Appears to be caused by https://bugzilla.mozilla.org/show_bug.cgi?id=990614
See https://jsfiddle.net/webpadawan/m7yLd5ow/
