### ISSUE TITLE
Extra white-space before item label when using `items` API

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-context-menu#222]
<img width="441" alt="screenshot 2019-02-21 at 12 49 04" src="https://user-images.githubusercontent.com/66382/53163748-71808680-35d7-11e9-9bbe-05b640b0423e.png">
<img width="417" alt="screenshot 2019-02-21 at 12 49 49" src="https://user-images.githubusercontent.com/66382/53163749-72191d00-35d7-11e9-875f-964770cc6464.png">

**Comment by jouni** [comment]
Since the items can be checked, there should be some enough space for the checkmark to appear. But now there’s more than that.

**Comment by web-padawan** [comment]
Confirmed to happen in desktop Safari 11. Cannot reproduce in any other browser though.
