### ISSUE TITLE
vaadin-context-menu - how to get rid of "Unable to preventDefault inside passive event listener invocation." exception on right mouse click

### ISSUE THREAD

**Issue by JuliaMelomed** [vaadin/vaadin-context-menu#225]
Hello,
I am using vaadin-context-menu component and it works ok for me, but I am getting following error "Unable to preventDefault inside passive event listener invocation." when doing right mouse click. My question is how to get rid of it.

**Comment by web-padawan** [comment]
Closing as duplicate of #192 

We will hopefully attempt to cover this as part of #220
