### ISSUE TITLE
Nested menu items do not work on Firefox

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-context-menu#226]
Nested menus do not open on Firefox. Tested on Firefox 65.0.2 on Windows 10 with a touch screen laptop (using a normal mouse).

![ezgif-4-0a7831b12496](https://user-images.githubusercontent.com/886091/54346663-22fe5f00-464e-11e9-9ca0-8855b45752ec.gif)

**Comment by Wnt** [comment]
Opening the nested menu seems to work with the keyboard, but there is no way to open the nested menu with the mouse.

**Comment by tomivirkki** [comment]
Wat? This doesn't open for you on FF? https://cdn.vaadin.com/vaadin-context-menu/4.3.2/demo/#context-menu-items-demos

**Comment by lkraav** [comment]
> Wat? This doesn't open for you on FF?

Correct, I just tested and can confirm - mouse clicks on submenu items do nothing.

**Comment by tomivirkki** [comment]
![ff-cm](https://user-images.githubusercontent.com/1222264/54365709-09720d00-4678-11e9-80ec-c99aaf97dab8.gif)

Works for me on Mac & FF 65.0.1
I'll try on Windows

**Comment by tomivirkki** [comment]
Works for me on Windows 10 & FF 65.0.2 also (the weird colors are due to running on VM)
![ff-cm-win](https://user-images.githubusercontent.com/1222264/54367255-c36a7880-467a-11e9-8112-fa2099de0342.gif)

**Comment by lkraav** [comment]
@tomivirkki discovered https://github.com/vaadin/vaadin-menu-bar today, and I'm experiencing the same thing there (Linux FF66).

**Comment by lkraav** [comment]
Followup: clicking on the menu item, even though it doesn't do anything visible, then hitting Space key works to unfold submenu.

**Comment by tomivirkki** [comment]
This is strange. Works fine for me on Ubuntu & Firefox 66 (VM)

![linux-menu-bar](https://user-images.githubusercontent.com/1222264/57697508-13a28e80-765c-11e9-925e-4ce68194a420.gif)

**Comment by lkraav** [comment]
I can report everything works in FF67, released earlier this week.

**Comment by tomivirkki** [comment]
Ok good news. Closing
