### ISSUE TITLE
The styling demo is not working properly

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-context-menu#239]
**Styling the Template Content** demo (https://cdn.vaadin.com/vaadin-context-menu/4.3.5/demo/#context-menu-styling-demos) doesn't have properly scoped styles, so seems to be broken.

**Comment by web-padawan** [comment]
Regression from vaadin/vaadin-overlay/commit/929101da11b520920e7bebaf5bde2f25767effd2

Will revert that commit. Apparently my refactor wasn't correct.
