### ISSUE TITLE
Pressing Up and Down when menu contains other element than list-box causes a JS error

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-context-menu#240]
`vaadin-context-menu-overlay.js:81 Uncaught TypeError: Cannot read property 'items' of null`

![vaadin-context-menu-keyboard-issues](https://user-images.githubusercontent.com/22416150/57916220-0e7f5280-789b-11e9-8edc-a1ab8a2d2256.gif)

Steps to reproduce:
 - open the context menu with a single element
 - press 'Up' on the keyboard

Example: [code](https://glitch.com/edit/#!/vaadin-context-menu-keyboard-nav), [live demo](https://vaadin-context-menu-keyboard-nav.glitch.me/)

**Comment by web-padawan** [comment]
Regression from b46f553

Will submit a fix to ensure that it only works when overlay is focused and it's child has items property.
