### ISSUE TITLE
pressing Down when menu is open causes a JS error (template, not with renderer)

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-context-menu#241]
`vaadin-context-menu-overlay.js:84 Uncaught TypeError: Cannot read property 'focus' of null`

![vaadin-context-menu-keyboard-issues](https://user-images.githubusercontent.com/22416150/57916220-0e7f5280-789b-11e9-8edc-a1ab8a2d2256.gif)

This issue appears only with a template, not with a renderer.
Steps to reproduce:
 - open the context menu with a single element
 - press 'Down' on the keyboard

Example: [code](https://glitch.com/edit/#!/vaadin-context-menu-keyboard-nav), [live demo](https://vaadin-context-menu-keyboard-nav.glitch.me/)

**Comment by web-padawan** [comment]
Regression from b46f5532931bf7f057babad69409e6d14034c4b1 and same issue as #240 

Let me close this one and continue there as the fix would be anyways the same.
