### ISSUE TITLE
Please make the `vaadin-context-menu-before-open` event official

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-context-menu#250]
The JavaScript Event `vaadin-context-menu-before-open` is useful for e.g. creating lazy context menus for grid as documented at https://github.com/vaadin/vaadin-context-menu-flow/issues/76 . However, the event is not present in the public API at https://vaadin.com/components/vaadin-context-menu/html-api . It would be great to 'publish' this API.

**Comment by tomivirkki** [comment]
The `<vaadin-context-menu>` web component doesn't have this event. I think you're referring to https://github.com/vaadin/vaadin-context-menu-flow/blob/master/vaadin-context-menu-flow/src/main/resources/META-INF/resources/frontend/contextMenuConnector.js#L32

**Comment by mvysny** [comment]
Ouch, you're right :) What would you suggest then? Sounds like it's an internal communication between the connector and the Java part, perhaps I should add a feature request to vaadin-context-menu-flow instead?

**Comment by gatanaso** [comment]
I agree with @tomivirkki that the web component does not need this event. This is an implementation detail of the flow context menu connector.

**Comment by web-padawan** [comment]
Closing per above comment https://github.com/vaadin/vaadin-context-menu/issues/250#issuecomment-523453021. The event doesn't exist in the web component.
