### ISSUE TITLE
Nested submenu is displayed inside much in its root menu in case it is displayed in the left side of the root menu. And the bug with right aligned.

### ISSUE THREAD

**Issue by hongduc-phan** [vaadin/vaadin-context-menu#261]
![Screenshot 2019-12-03 at 17.10.25.png](https://images.zenhubusercontent.com/5dc0215f5fcf0b0001851bd0/82231f41-e36f-4206-8387-a2042cbf768b)

The photo shows that the nested menu is displayed inside much in the root menu, instead of its right edge (nested submenu) is near(or inside but in a little bit ) the left edge of the root menu.

But with the right aligned for in case the width is small enough the submenu is displayed in the right, there is a bug that submenu is displayed above the root menu. please see the photo above.![Screenshot 2019-12-09 at 16.11.13.png](https://images.zenhubusercontent.com/5dc0215f5fcf0b0001851bd0/0e396e20-ab7a-451e-941d-87897017c630)

**Comment by Haprog** [comment]
Looks like this was fixed by #265 but wanted to make it clear (for future reference) since it was a bit hard to check due to the couple of related PRs that were closed as unmerged.
