### ISSUE TITLE
context-menu only works once

### ISSUE THREAD

**Issue by dlcooper** [vaadin/vaadin-context-menu#28]
Just playing with this and found that

```html
<vaadin-split-layout>
	<div></div>
	<div>
		<div id="latin">
		    Lorem ipsum dolor sit amet. Consectetur adipiscing elit.
		</div>
		<vaadin-context-menu selector="latin">
			<div>You've clicked on a piece of text that's in Latin.</div>
		</vaadin-context-menu>
	</div>
</vaadin-split-layout>
```

only displays the context menu the first time through.  For some reason the context menu thinks the target changes and so it removes the listener for the contextmenu event.

The context menu works well until I added the vaadin-split-layout element

**Comment by samiheikki** [comment]
Hi @dlcooper 

Looking at your code sample looks like you are not wrapping the #latin div inside the context-menu's template. Please look at how it is done in this demo: https://cdn.vaadin.com/vaadin-core-elements/master/vaadin-context-menu/demo/index.html
