### ISSUE TITLE
Remove white stripe when backdrop is resized

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-context-menu#41]
When scrolling up/down in mobile (android and ios) there is a white stripe for a few milliseconds.

Screenshots:
- Droid: http://g.recordit.co/QZYWpiKOXF.gif
- iOS: http://g.recordit.co/aYCT3VKsqR.gif

Related with #39

**Comment by tomivirkki** [comment]
No longer relevant. Closing.
