### ISSUE TITLE
No close event?

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-context-menu#46]
Is there a way to recognize if the context-menu was closed/is closing?

As I want to set a visual selection to the element the context-menu was opened for, i need to delete that selection when the context-menu gets closed. And therefore I need a closing event. Only knowing when a context-menu entry was clicked isn't enough because that's only half the truth.

Any advises?

**Comment by Saulis** [comment]
Hi!

We actually have a private `_opened` property in there which has `notify: true`, so you should be able to listen to `_opened-changed` event. 

I think we could consider making this property public.

**Comment by tomivirkki** [comment]
The overlay is currently built with Polymer's `iron-overlay-behavior` so whenever it closes, it fires an "iron-overlay-closed" event. That should also work (even though it's not part of our public API either).
