### ISSUE TITLE
First context-menu item is getting :hover state without actual hovering (advance example with Grid)

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-context-menu#54]
![recorded](https://cloud.githubusercontent.com/assets/6059356/21293590/41f15998-c532-11e6-9bc2-ab7ea99617d4.gif)

### Browsers Affected

- Chrome/Linux

**Comment by jouni** [comment]
Closing as invalid. That’s not a hover state, it’s the focused state instead. And since it’s paper-listbox/menu, we can’t do much about that.

Closely related to #55
