### ISSUE TITLE
Context menu remembers and shows clicked item from previuos opened one

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-context-menu#55]
![recorded](https://cloud.githubusercontent.com/assets/6059356/21293615/e4b8f672-c532-11e6-96eb-768684073639.gif)

### Browsers Affected

- Chrome/Linux

**Comment by platosha** [comment]
That’s a `<paper-menu>` feature. There is a workaround to make it invisible:

```
<paper-menu selected-class="not-defined">...</paper-menu>
```

Documented in PR #51, both in demos and in asciidoc.

**Comment by limonte** [comment]
`selected-class` isn't a workaround, but a hack. There shouldn't be any preselected item in new context menu.

**Comment by platosha** [comment]
The feature is fused in and not available for disabling in the `<paper-menu>`.

Removing the styling for the selected item is, compared with other options, less hacky in this case.

**Comment by jouni** [comment]
The selected style is not an issue with Valo out-of-the-box.

But, I also agree that we should reset the focused item to `undefined`  when the overlay is opened. IMO it would be fine if this only works for `vaadin-list-box`.

**Comment by web-padawan** [comment]
Closing in favor of #160 and because this issue is for outdated context-menu version.
