### ISSUE TITLE
After introducing iron-overlay-backdrop, context-menu is not getting the right context on two right-clicks one after another

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-context-menu#65]
![recorded](https://cloud.githubusercontent.com/assets/6059356/21975070/3ac24832-dbd3-11e6-9399-d5ad6e8a17ab.gif)

**Comment by samiheikki** [comment]
+1

**Comment by jariberi** [comment]
# Still a issue:
This issue is still a issue in 3.0.0-stable. Two consecutive right click, open browser's context menu, not vaadin-context-menu. I use in a vaadin-grid.

**Comment by tomivirkki** [comment]
Looks like [this listener](https://github.com/vaadin/vaadin-context-menu/blob/a9d46aba44cbb29b474f3221443a58935c477ada/src/vaadin-context-menu.html#L305) no longer serves the purpose it was originally meant for. We'll need to change it to listen for "contextmenu" events globally and take action when `opened`.
