### ISSUE TITLE
Right-click on context menu should work like left-click

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-context-menu#68]
Actual: right-click on context menu triggers another context menu with the same context.

Expected: right-click on context menu should work like left-click and select a context menu item under the cursor

**Comment by tomivirkki** [comment]
The "actual" part doesn't occur in latest 3 series alpha.

"Expected" part is debatable. Since our context-menu isn't just a list of clickable options but you can place virtually anything inside, the context-menu shouldn't have an opinion on what right-click should do.

**Comment by limonte** [comment]
> "Expected" part is debatable. Since our context-menu isn't just a list of clickable options but you can place virtually anything inside, the context-menu shouldn't have an opinion on what right-click should do.

Yeah, I forgot the grid-inside use-case :D

**Comment by jouni** [comment]
IMO this is a wontfix. This is of course just my assumption, but I think “the common user” just uses the primary mouse button to interact with the items. If they happen to click with the secondary button by mistake, it doesn’t cause any damage.

Personally, as a developer, I really like the fact that I can right click on the menu items and use “Inspect Element”.
