### ISSUE TITLE
Overlay `with-backdrop` prevents menu click

### ISSUE THREAD

**Issue by zbury** [vaadin/vaadin-context-menu#69]
This [commit](https://github.com/vaadin/vaadin-context-menu/commit/78ee9e110da470a780610f0317cd6dcb02627499) seems to have introduced a bug where in certain situations the overlay is actually drawn on top of the menu. This results in the overlay capturing any attempts to click/tap on the menu (menu is closed, never registers click / tap event). 

I believe this issue is related to this [discussion of overlay limitations](https://github.com/PolymerElements/paper-dialog/issues/79) demonstrated here 
http://jsbin.com/cecuqiviye/1/edit?html,output. It seems the Polymer Team is working on ["overlays 2.0"](https://github.com/PolymerElements/iron-overlay-behavior/pull/155) to address these limitations.

In the meantime, simply removing `with-backdrop` fixes the issue for me. Not sure how that affects the rest of the commit.

**Comment by tomivirkki** [comment]
Hi @zbury,

What kind of a situation do you mean exactly? Does this occur on some specific browser/environment?

Can you modify the following example so that the issue can be reproduced?
http://jsbin.com/xiqafuyete/edit?html,output

**Comment by zbury** [comment]
@tomivirkki I believe this occurs when a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) is formed that "traps" the menu. Check out this example https://jsbin.com/tinohav/1/edit?html,output 

Menu click doesn't register for me Chrome, Firefox and Safari (MacOS).

**Comment by tomivirkki** [comment]
Ah, yes indeed. This is an issue with `iron-overlay-behavior` including the overlay inside the component.
We’ve bumped into similar stuff before: https://github.com/vaadin/vaadin-date-picker/issues/133. With `<vaadin-combo-box>` this has been resolved by using our own solution that moves the overlay from the component right under `<body>` on open. We’re planning on extracting that as a shared overlay component that we could use with `<vaadin-date-picker>` and `<vaadin-context-menu>` also.

Thanks for reporting, marking this as a bug

**Comment by jouni** [comment]
I suppose this issue is something we are not considering to fix in the previous versions, and encourage users to upgrade to the latest major that doesn’t use iron-overlay-behavior anymore.

**Comment by tomivirkki** [comment]
All the elements with an overlay/dropdown are now using the shared `<vaadin-overlay>`. Closing.
