### ISSUE TITLE
Polymer 2.0 Support

### ISSUE THREAD

**Issue by Saulis** [vaadin/vaadin-context-menu#70]
- Use `v2.0.0-rc1`
- Aim for Hybrid if feasible
- ~~Consider reusing the overlay from `<vaadin-combo-box>`~~

- Follow steps from https://www.polymer-project.org/2.0/docs/upgrade for more details.

**Comment by jouni** [comment]
Regarding the demos, we need to replace any paper-menu elements with paper-listbox apparently: https://github.com/PolymerElements/paper-menu/pull/112#issuecomment-294560068
