### ISSUE TITLE
Overlay doesn’t stay open

### ISSUE THREAD

**Issue by zant95** [vaadin/vaadin-context-menu#78]
I have the same issue as #71 in Polymer 2.0 and Chrome 58 with the following example.
```html
<vaadin-context-menu>
	<template>
		<paper-listbox>
			<paper-item>First menu item</paper-item>
			<paper-item>Second menu item</paper-item>
		</paper-listbox>
	</template>

	<paper-listbox>
		<paper-item>This item has the context menu provided in the above template.</paper-item>
		<paper-item>Another item with the context menu.</paper-item>
	</paper-listbox>
</vaadin-context-menu>
```

**Comment by Saulis** [comment]
The provided snippet seems to work just fine at least on my Chrome 58 on macOS: https://jsfiddle.net/Saulis/f3dph6f5/ 
Can you provide a fiddle which would reproduce the issue?

**Comment by zant95** [comment]
Sorry, forget to say that I'm facing this issue on phone, on a real phone and Chrome DevTools device emulator.

The link you provided seems to have the issue.

**Comment by Saulis** [comment]
@zant95 thanks for the clarification! I can also see the issue in the fiddle with Chrome DevTools. However, https://cdn.vaadin.com/vaadin-context-menu/2.0.0-alpha1/demo/ demos seem to work? Can you confirm this?

**Comment by zant95** [comment]
The demo works fine. I think that the issue is related with the "tap" event fired by the "paper-item".

**Comment by Saulis** [comment]
@zant95 can you verify if the branch `prevent-touchend-capture` fixes the issue for you?

**Comment by zant95** [comment]
Yes, it works!
