### ISSUE TITLE
Some examples don’t work in iOS Safari

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-context-menu#83]
For the following examples the context menu is not shown in iOS Safari:

- Menu Item Events
- Advanced / Using with Vaadin Grid

In addition, in the “Filtering Menu Targets” example, native text selection on long tap gets prevented for the second paragraph both in iOS and Android.

**Comment by tomivirkki** [comment]
Fixed in https://github.com/vaadin/vaadin-context-menu/pull/98
