### ISSUE TITLE
Event when context-menu is opening?

### ISSUE THREAD

**Issue by Mika83AC** [vaadin/vaadin-context-menu#88]
Hello everyone,

is there a context-menu opening event? I'd like to highlight a list entry the context-menu was opened for, and therefore I need to know when it's opening and which item was clicked to perform the list entry selection.

Can't find anything about this in the docs.

Regards,
Michael

**Comment by platosha** [comment]
You can detect the `<vaadin-context-menu>` opening by listening for the same event that triggers the opening.

The opening event name configurable in the `openOn` property of the context menu. By default, it uses `vaadin-contextmenu`, which is a [Polymer gesture event](https://www.polymer-project.org/2.0/docs/devguide/gesture-events).

**Comment by Mika83AC** [comment]
Ahm... sorry to bother you, but how to subscribe to this event?

Neither 
`Polymer.Gestures.addListener(this, 'vaadin-contextmenu', e => _contextMenuOpening(e));`
nor 
`Polymer.Gestures.addListener(this.$.contextMenu, 'vaadin-contextmenu', e => _contextMenuOpening(e));`
works.

**Comment by platosha** [comment]
This works for me:

```javascript
Polymer.Gestures.addListener(this.$.contextMenu, 'vaadin-contextmenu', e => console.log(e));
```

**Comment by Mika83AC** [comment]
Hm... strange. Can you give me a jsbin link to your working example? Perhaps I can spot the difference between our implementations then.

**Comment by Mika83AC** [comment]
Got it! I didn't wraped the grid with the context-menu. Instead I let the menu listen to the grid:

`this.$.contextMenu.listenOn = this.$.grid;`

So now I changed the addListener to

`Polymer.Gestures.addListener(this.$.grid, 'vaadin-contextmenu', e => console.log(e));`

and the event gets logged.

But is there any chance to know which row the context-menu was opened for in the vaadin-contextmenu event? Otherwise I can't set the row as activeItem so that the user sees that the clicked row is the active row.

**Comment by platosha** [comment]
Couple of steps:

1. In your grid column templates, wrap the text content with an element, if it is not wrapped already. For example:
  `<div class="grid-content">[[item.data]]</div>`

2. Add bindings on the column content wrapper and share the item index/data. For example, to share indexes with an attribute:
  `<div class="grid-content" data-index$="[[index]]">[[item.data]]</div>`

3. In the opening event listener, you can find the wrapper in the `event.composedPath()` and extract the data you bound back:

  ```javascript
  const index = e.composedPath()
    .filter(el => el.classList && el.classList.contains('grid-content'))[0]
    .getAttribute('data-index');
  ```

We have an example of a grid and a context menu with add and remove actions using the similar approach: https://cdn.vaadin.com/vaadin-context-menu/2.0.0-beta1/demo/advanced.html#using-with-vaadin-grid

**Comment by Mika83AC** [comment]
That's it! Already had the data-index attributes for the context-menu-item-clicks, but I didn't know how to use this in the context-menu-opening event.

Thx for your assistance @platosha! :)
