### ISSUE TITLE
Fixes for touch devices

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu#96]
In https://cdn.vaadin.com/vaadin-context-menu/3.0.0-alpha2/demo/ Menu Item Events part does not work with touch devices

Also the context-menu in Grid part of the demo does not work with touch devices

**Comment by manolo** [comment]
Menu Item seems working in touch devices.
Grid context-menu, closes the menu on open, is that the problem?

http://g.recordit.co/q212sQTiJ5.gif
