### ISSUE TITLE
Can not scroll the Long Menu demo

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-context-menu#97]
Can not scroll the Long Menu demo on desktop nor touch (iOS 10)

**Comment by platosha** [comment]
Currently, the context menu does not respect viewport constrains.

This is a regression originating from using `<vaadin-overlay>` in the context menu.

After taking a deep look on this, I would propose implementing this as a feature in the overlay. Any overlay user needs to respect the viewport, including the dialog and the combo-box.

See the overlay feature issue: vaadin/vaadin-overlay#22.
